### ISSUE TITLE
Add acronym checking

### ISSUE THREAD

**Issue by lilyosah** [lilyosah/NLP-Task-Parser#5]

**Comment by ckjones818** [comment]
I tried to accomplish this using the scispacy library and its AbbreviationDetector class, but that seems only to succeed when a sentence is formatted with the extended acronym present like so: "The University of California, Los Angeles (UCLA) is a big school" (i.e. from that point on it would parse "UCLA" into "The University of California, Los Angeles"). I tried to figure out if there were any other ways to work around this but came up empty. I've been looking into [the NLPre library](https://github.com/NIHOPA/NLPre), which claims to have acronym-parsing capabilities, but the documentation is sparse and I can't get it to install on mine anyways because of pip-related errors. However, from what I can tell it looks like it might be promising.

**Comment by bcchin** [comment]
I added regex so that it will detect abbreviations like "bio" for "biology" or any situation where you're not completely writing out the full name of the group. Right now, I'm currently working on improving the algorithm so it can detect situations like abbreviations (ex. "cs" for computer science") or "compsci / comp sci" for "computer science"

**Comment by bcchin** [comment]
I added to the algorithm so now it can detect acronyms like "cs" for "computer science" but to be honest, I'm not sure how to handle situations like "compsci / comp sci" for "computer science"

**Comment by lilyosah** [comment]
Great job Bonnie!!! 👏👏👏
